const moviesTypes = {
  GET_MOVIES: "GET_MOVIES",
  GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
  GET_MOVIES_FAILED: "GET_MOVIES_FAILED",

  GET_MOVIE: "GET_MOVIE",
  GET_MOVIE_SUCCESS: "GET_MOVIE_SUCCESS",
  GET_MOVIE_FAILED: "GET_MOVIE_FAILED",

  GET_SIMILAR_MOVIES: "GET_SIMILAR_MOVIE",
  GET_SIMILAR_MOVIES_SUCCESS: "GET_SIMILAR_MOVIE_SUCCESS",
  GET_SIMILAR_MOVIES_FAILED: "GET_SIMILAR_MOVIE_FAILED",

  GET_GENRES: "GET_GENRES",
  GET_GENRES_SUCCESS: "GET_GENRES_SUCCESS",
  GET_GENRES_FAILED: "GET_GENRES_FAILED",

  SEARCH_MOVIES: "SEARCH_MOVIES",
  SEARCH_MOVIES_SUCCESS: "SEARCH_MOVIES_SUCCESS",
  SEARCH_MOVIES_FAILED: "SEARCH_MOVIES_FAILED",
};

export default moviesTypes;
